version: '3'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - "24485:7000"   # Cassandra inter-node communication
      - "24486:7001"   # Cassandra JMX port
      - "24487:7199"   # Cassandra JMX remote port
      - "24488:9042"   # Cassandra CQL native transport
      - "24489:9160"   # Cassandra Thrift RPC
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - cassandra-net

volumes:
  cassandra-data:

networks:
  cassandra-net:
    driver: bridge

